### ISSUE TITLE
re-run Parikh

### ISSUE THREAD

**Issue by abrj** [danielvarab/contradiction-detection#2]
Re-run with these embeddings:
Glove.6B.300d
Glove.840B.300d
Glove.840B.300 + MCE (500d)

**Comment by danielvarab** [comment]
Status

- [ ] Glove.6B.300d
- [X] Glove.840B.300d
- [ ] Glove.840B.300 + MCE (500d)

**Comment by danielvarab** [comment]
Fun fact. Seems like the longest sentence in the training set is 401 words long.

`awk 'length > max_length { max_length = length; longest_line = $0 } END { print longest_line }' ./file`

**Comment by danielvarab** [comment]
This issue is in fact continuation of issue #1 .

**Comment by abrj** [comment]
This task is related to re-running Parikh with Multi NLI data set, right?
